### PR TITLE
Support multiple exceptions in a single response

### LINKED ISSUE #11: How can we have all errors in a single response?
Hello, I'm trying to figure out if this is included (or if planned for later on) where we get all errors in a single JSON response.
For example, if I were to send a bad POST request with two blank fields, I'd only get an error for one of them:
```
{
    "type": "validation_error",
    "code": "blank",
    "detail": "This field may not be blank.",
    "attr": "FIELD_ONE"
}
```
How can we get something like:
```
errors: [
    {
        "type": "validation_error",
        "code": "blank",
        "detail": "This field may not be blank.",
        "attr": "FIELD_ONE"
    },
    {
        "type": "validation_error",
        "code": "blank",
        "detail": "This field may not be blank.",
        "attr": "FIELD_TWO"
    }
]
```

It really helps with sign up forms for example, since the user gets to see all failing fields the first time, instead of fixing them one by one every failing request.

### PR DESCRIPTION
**Pull request by abtinmo**
closes #11 

adds support for returning all errors instead of picking one of them.

### CODE REVIEW

**Comment by abtinmo** [comment]
there is some issue with mypy:

"BaseException" has no attribute "get_codes"

i silenced the error for now,  should i create custom Typing class?

**Comment by paolodamico** [comment]
Thanks for this @abtinmo!! Will take a look during the week to get it merged ASAP

**Comment by abtinmo** [comment]
> Thanks for this @abtinmo!! Will take a look during the week to get it merged ASAP
Hey @paolodamico , please tell me if anything should be changed or i can improve the PR. i would be happy to help ;)

**Comment by paolodamico** [comment]
@posthog-bot please add @abtinmo for code

**Review by paolodamico — APPROVED** [review]
Thank you so much for taking the time to tackle this @abtinmo! Looks great! Made some adjustments to avoid changing the overall shape of the response when multiple exceptions occur.


Will push a release today or tomorrow as I want to include a few other improvements that I hadn't had a chance to get too.

**Pull request merged**
